BoxLayout:
    orientation: 'vertical'         # 追加

    BoxLayout:
        orientation: 'vertical'     # 追加
 
        Button:
            text: "Hello World"
        Label:
            text: "Hello World2"
        TextInput:
            text: "Hello World3"

    BoxLayout:
        orientation: 'horizontal'   # 横並び

        Button:
            text: "Hello World4"
        Label:
            text: "Hello World5"
        TextInput:
            font_name: "ume-pgc4.ttf"     #追加
            text: "こんにちは"